<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>UserAuthentication</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-09-08T23:34:29</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f49bee16-4ab1-4d21-a89b-0d85217e1377</testSuiteGuid>
   <testCaseLink>
      <guid>146f77cd-429e-497d-a05c-cdecc690d0fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8eb59c4-0716-4ee6-97b8-d86926d113a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c8766a3-5641-45c8-849d-593de0fda7c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6af5a8f-04ab-4d96-a735-e0ecfb866f79</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
